version: "3.8"
services:
    cloudreg:
        image: neurodata/cloudreg
        shm_size: 20gb
        secrets:
            - cloudvolume_credentials

secrets:
    cloudvolume_credentials:
        file: "~/.cloudvolume/secrets/aws-secret.json"
